version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rag